id: P004246
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 11:04:23.591227
source_metadata:
  id: bdr:W1KG25449
  title: བཅའ་ཁྲིམས་ཤེས་བྱའི་ཟེགས་མ།
  author: ''
  volumes:
    c8fc93a445ad4b3cb808f7fcbc887364:
      image_group_id: I1KG25451
      title: ''
      volume_number: 1
      total_pages: 472
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
